=== alhenk/aquarium/resources/Item.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xs:element name="Item">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="description" type="xs:string"></xs:element>
				<xs:element name="price" type="xs:double"></xs:element>
				<xs:element name="Animal" type="Animal"></xs:element>
			</xs:sequence>
			<xs:attribute name="uid" type="xs:string"></xs:attribute>
			<xs:attribute name="name" type="xs:string"></xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="Fish">
		<xs:sequence>
			<xs:element name="pHMax" type="xs:double"></xs:element>
			<xs:element name="pHMin" type="xs:double"></xs:element>
			<xs:element name="waterTemperatureMax" type="xs:double"></xs:element>
			<xs:element name="waterTemperatureMin" type="xs:double"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Animal">
		<xs:sequence>
			<xs:element name="sizeMax" type="xs:double"></xs:element>
			<xs:element name="tankVolumeMin" type="xs:double"></xs:element>
			<xs:element name="taxonomy" type="xs:string"></xs:element>
			<xs:element name="Fish" type="Fish"></xs:element>
		</xs:sequence>
	</xs:complexType>

</xs:schema>

=== alhenk/aquarium/resources/Item.xml
<?xml version="1.0" encoding="UTF-8"?>
<Item uid="asdf" name="seahorse" xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	xmlns="urn" xsi:schemaLocation="urn Item.xsd">
	<description>NA</description>
	<price>120.3</price>
	<Animal>
		<sizeMax>10.2</sizeMax>
		<tankVolumeMin>30</tankVolumeMin>
		<taxonomy>NA</taxonomy>
		<Fish>
			<pHMax>16.1</pHMax>
			<pHMin>11.3</pHMin>
			<waterTemperatureMax>25.0</waterTemperatureMax>
			<waterTemperatureMin>18.0</waterTemperatureMin>
		</Fish>
	</Animal>
</Item>
